sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
